   SUBROUTINE IXGB(LUGB,LSKIP,LGRIB,NLEN,NNUM,CBUF)
!$$$  SUBPROGRAM DOCUMENTATION BLOCK
!
! SUBPROGRAM: IXGB           MAKE INDEX RECORD
!   PRGMMR: IREDELL          ORG: W/NMC23     DATE: 95-10-31
!
! ABSTRACT: THIS SUBPROGRAM MAKES ONE INDEX RECORD.
!       BYTE 001-004: BYTES TO SKIP IN DATA FILE BEFORE GRIB MESSAGE
!       BYTE 005-008: BYTES TO SKIP IN MESSAGE BEFORE PDS
!       BYTE 009-012: BYTES TO SKIP IN MESSAGE BEFORE GDS (0 IF NO GDS)
!       BYTE 013-016: BYTES TO SKIP IN MESSAGE BEFORE BMS (0 IF NO BMS)
!       BYTE 017-020: BYTES TO SKIP IN MESSAGE BEFORE BDS
!       BYTE 021-024: BYTES TOTAL IN THE MESSAGE
!       BYTE 025-025: GRIB VERSION NUMBER
!       BYTE 026-053: PRODUCT DEFINITION SECTION (PDS)
!       BYTE 054-095: GRID DEFINITION SECTION (GDS) (OR NULLS)
!       BYTE 096-101: FIRST PART OF THE BIT MAP SECTION (BMS) (OR NULLS)
!       BYTE 102-112: FIRST PART OF THE BINARY DATA SECTION (BDS)
!       BYTE 113-152: (OPTIONAL) BYTES 41-80 OF THE PDS
!
! PROGRAM HISTORY LOG:
!   95-10-31  IREDELL
!
! USAGE:    CALL WRGI1R(LUGB,LSKIP,LGRIB,LUGI)
!   INPUT ARGUMENTS:
!     LUGB         INTEGER LOGICAL UNIT OF INPUT GRIB FILE
!     LSKIP        INTEGER NUMBER OF BYTES TO SKIP BEFORE GRIB MESSAGE
!     LGRIB        INTEGER NUMBER OF BYTES IN GRIB MESSAGE
!     NLEN         INTEGER LENGTH OF EACH INDEX RECORD IN BYTES
!     NNUM         INTEGER INDEX RECORD NUMBER TO MAKE
!   OUTPUT ARGUMENTS:
!     CBUF         CHARACTER*1 (MBUF) BUFFER TO RECEIVE INDEX DATA
!
! SUBPROGRAMS CALLED:
!   GBYTE        GET INTEGER DATA FROM BYTES
!   SBYTE        STORE INTEGER DATA IN BYTES
!   BAREAD       BYTE-ADDRESSABLE READ
!
! ATTRIBUTES:
!   LANGUAGE: CRAY FORTRAN
!
!$$$
   CHARACTER CBUF(*)
   PARAMETER(LINDEX=152)
   PARAMETER(IXSKP=0,IXSPD=4,IXSGD=8,IXSBM=12,IXSBD=16,IXLEN=20,               &
             IXVER=24,IXPDS=25,IXGDS=53,IXBMS=95,IXBDS=101,                    &
             IXPDX=112)
   PARAMETER(MXSKP=4,MXSPD=4,MXSGD=4,MXSBM=4,MXSBD=4,MXLEN=4,                  &
             MXVER=1,MXPDS=28,MXGDS=42,MXBMS=6,MXBDS=11,                       &
             MXPDX=40)
   CHARACTER CBREAD(LINDEX),CINDEX(LINDEX)
   ! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   !  INITIALIZE INDEX RECORD AND READ GRIB MESSAGE
   !
   DO I=1,LINDEX
     CINDEX(I)=CHAR(0)
   ENDDO
   CALL SBYTE(CINDEX,LSKIP,8*IXSKP,8*MXSKP)
   CALL SBYTE(CINDEX,LGRIB,8*IXLEN,8*MXLEN)
   ! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   !  PUT PDS IN INDEX RECORD
   !
   ISKPDS=8
   IBSKIP=LSKIP
   IBREAD=ISKPDS+MXPDS
   CALL BAREAD(LUGB,IBSKIP,IBREAD,LBREAD,CBREAD)
   IF(LBREAD.NE.IBREAD) RETURN
   CINDEX(IXVER+1)=CBREAD(8)
   CALL SBYTE(CINDEX,ISKPDS,8*IXSPD,8*MXSPD)
   CALL GBYTE(CBREAD,LENPDS,8*ISKPDS,8*3)
   CALL GBYTE(CBREAD,INCGDS,8*ISKPDS+8*7+0,1)
   CALL GBYTE(CBREAD,INCBMS,8*ISKPDS+8*7+1,1)
   ILNPDS=MIN(LENPDS,MXPDS)
   ! DO I=1,LINDEX
     CINDEX(1)(IXPDS+1:IXPDS+ILNPDS)=CBREAD(1)(ISKPDS+1:ISKPDS+ILNPDS)
   ! ENDDO
   ISKTOT=ISKPDS+LENPDS
   ! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   !  PUT PDS EXTENSION IN INDEX RECORD
   !
   IF(LENPDS.GT.40) THEN
      ISKPDX=ISKPDS+40
      IBSKIP=LSKIP+ISKPDX
      IBREAD=MXPDX
      CALL BAREAD(LUGB,IBSKIP,IBREAD,LBREAD,CBREAD)
      IF(LBREAD.NE.IBREAD) RETURN
      ILNPDX=MIN(LENPDS-40,MXPDX)
      ! DO I=1,LINDEX
        CINDEX(1)(IXPDX+1:IXPDX+ILNPDX)=CBREAD(1)(1:ILNPDX)
      ! ENDDO
   ENDIF
   ! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   !  PUT GDS IN INDEX RECORD
   !
   IF(INCGDS.NE.0) THEN
      ISKGDS=ISKTOT
      IBSKIP=LSKIP+ISKGDS
      IBREAD=MXGDS
      CALL BAREAD(LUGB,IBSKIP,IBREAD,LBREAD,CBREAD)
      IF(LBREAD.NE.IBREAD) RETURN
      CALL SBYTE(CINDEX,ISKGDS,8*IXSGD,8*MXSGD)
      CALL GBYTE(CBREAD,LENGDS,0,8*3)
      ILNGDS=MIN(LENGDS,MXGDS)
      ! DO I=1,LINDEX
        CINDEX(1)(IXGDS+1:IXGDS+ILNGDS)=CBREAD(1)(1:ILNGDS)
      ! ENDDO
      ISKTOT=ISKGDS+LENGDS
   ENDIF
   ! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   !  PUT BMS IN INDEX RECORD
   !
   IF(INCBMS.NE.0) THEN
      ISKBMS=ISKTOT
      IBSKIP=LSKIP+ISKBMS
      IBREAD=MXBMS
      CALL BAREAD(LUGB,IBSKIP,IBREAD,LBREAD,CBREAD)
      IF(LBREAD.NE.IBREAD) RETURN
      CALL SBYTE(CINDEX,ISKBMS,8*IXSBM,8*MXSBM)
      CALL GBYTE(CBREAD,LENBMS,0,8*3)
      ILNBMS=MIN(LENBMS,MXBMS)
      ! DO I=1,LINDEX
        CINDEX(1)(IXBMS+1:IXBMS+ILNBMS)=CBREAD(1)(1:ILNBMS)
      ! ENDDO
     ISKTOT=ISKBMS+LENBMS
   ENDIF
   ! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   !  PUT BDS IN INDEX RECORD
   !
   ISKBDS=ISKTOT
   IBSKIP=LSKIP+ISKBDS
   IBREAD=MXBDS
   CALL BAREAD(LUGB,IBSKIP,IBREAD,LBREAD,CBREAD)
   IF(LBREAD.NE.IBREAD) RETURN
   CALL SBYTE(CINDEX,ISKBDS,8*IXSBD,8*MXSBD)
   CALL GBYTE(CBREAD,LENBDS,0,8*3)
   ILNBDS=MIN(LENBDS,MXBDS)
   ! DO I=1,LINDEX
     CINDEX(1)(IXBDS+1:IXBDS+ILNBDS)=CBREAD(1)(1:ILNBDS)
   ! ENDDO
   
   ! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   !  STORE INDEX RECORD
   !
   NSKIP=NLEN*(NNUM-1)
   NSTORE=MIN(NLEN,LINDEX)
   ! DO I=1,LINDEX
     CBUF(1)(NSKIP+1:NSKIP+NSTORE)=CINDEX(1)(1:NSTORE)
     CBUF(1)(NSKIP+NSTORE+1:NSKIP+NLEN)=CHAR(0)
   ! ENDDO
   
   ! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   RETURN
   END
