   SUBROUTINE DATIMX(NOW)
!$$$  SUBPROGRAM DOCUMENTATION BLOCK
!                .      .    .                                       .
! SUBPROGRAM:    DATIMX      PROVIDES DATE/TIME INFORMATION
!   PRGMMR: R.E.JONES        ORG: W/NMC42    DATE: 93-11-10
!
! ABSTRACT: DATIMX PROVIDES YOU WITH DATE AND TIME INFORMATION 
!   THAT CAN BE USED BY YOUR PROGRAMS. IT HAS THE SAME OUTPUT
!   AS IBM SUBROUTINE DATIMX IN IBM VS FORTRAN 2.5
!
! PROGRAM HISTORY LOG:
!   93-11-10  R. E. JONES   SAME AS IBM VS FORTRAN VER 2.5
!
! USAGE:    CALL DATIMX(NOW)
!   OUTPUT ARGUMENT LIST:  
!     NOW       - INTEGER*4 ARRAY WITH 14 WORDS
!     
!     ELEMENT   CONTENTS
!
!     1         THE VALUE OF THE CLOCK EXPRESSED AS A POSTITIVE 
!               INTEGER, SET TO 1, SET TO -1 IF INVALID
!     2         MILLISECONDS (0-990) PRECISE TO THE HUNDREDTHS              
!               POSITION, SET TO ZERO ON SGI
!     3         SECONDS (0-59)
!     4         MINUTES (0-59)
!     5         HOUR USING A 24-HOUR CLOCK (0-23)
!     6         DAY OF MONTH  (1-31)
!     7         MONTH OF YEAR (1-12)
!     8         YEAR (4 DIGIT, FOR EXAMPLE: 1993)
!     9         RESERVED. VALUE RETURNED AS -1.
!               WE ARE GOING TO PUT THE JULIAN DAY NUMBER HERE
!     10        HOUR USING 12-HOUR CLOCK (1-12)
!     11        AM/PM INDICATOR. 1 IS RETURNED FOR AM, 2 FOR PM.
!     12        DAY OF WEEK (1-7) BEGINNING WITH SUNDAY
!     13        DAY OF YEAR (1-366)
!     14        YEAR (2 DIGIT, FOR EXAMPLE: 93)
!
!   SUBPROGRAMS CALLED:
!     LIBRARY:
!      SYSTEM  - IDATE, ITIME
!       W3LIB  - IW3JDN
!
! ATTRIBUTES:
!   LANGUAGE: SUN 1.4 FORTRAN 77
!   MACHINE:  SUN SPARCstation 1+, 2, 10, SPARCserver 630, 690
!
!$$$
!
   INTEGER  ::  NOW(14)
   INTEGER  ::  JDATE(3)
   INTEGER  ::  JTIME(3)
!
!     ARRAY JDATE =  DAY   MONTH  YEAR (4 DIGIT)
!
   CALL IDATE(JDATE)
!
   NOW(8) = JDATE(3)
   NOW(7) = JDATE(2)
   NOW(6) = JDATE(1)

   CALL ITIME(JTIME)
   !
   !     ARRAY JTIME =  HOUR  MINUTE SECOND
   !
   NOW(5) = JTIME(1)
   NOW(4) = JTIME(2)
   NOW(3) = JTIME(3)
!
   NOW(1)  =  1
! 
   IF (NOW(8).GE.2000) THEN
     NOW(14) = NOW(8) - 2000
   ELSE
     NOW(14) = NOW(8) - 1900
   END IF
!
   IF (NOW(5).GT.11) THEN
     NOW(11) = 2
     NOW(10) = NOW(5) - 12
   ELSE
     NOW(11) = 1
     NOW(10) = NOW(5)
   END IF
   !
   !     COMPUTE JULIAN DAY NUMBER  (JAN 1,1960 = 2,436,935 )
   !
   JDN    = IW3JDN(NOW(8),NOW(7),NOW(6))
   NOW(9) = JDN
   !
   !     COMPUTE DAY OF WEEK FROM JULIAN DAY NUMBER
   !
   NOW(12) = MOD((JDN + 1),7) + 1
   IYR     = NOW(8)
   !
   !     COMPUTE DAY OF YEAR (1-366) USING JULIAN DAY NUMBER
   !
   NOW(13) = JDN -                                                             &
     (-31739 +1461 * (IYR+4799) / 4 - 3 * ((IYR+4899)/100)/4)
   !
   !     NEXT 3 LINES WORK ON 1+, 2, with FORTRAN 1.4, BUT DO NOT
   !     WORK ON MODEL 10 WITH 2.01 FORTRAN
   !
!     SEC1   = SECNDS(0)
!     SEC2   = AINT(SEC1)
!     NOW(2) = (SEC1 - SEC2) * 1000.0
!
   NOW(2) = 0
!
   RETURN
   END
