   SUBROUTINE GETGIR(LUGB,MSK1,MSK2,MNUM,MBUF,CBUF,NLEN,NNUM,IRET)
!$$$  SUBPROGRAM DOCUMENTATION BLOCK
!
! SUBPROGRAM: GETGIR         READS A GRIB INDEX FILE
!   PRGMMR: IREDELL          ORG: W/NMC23     DATE: 95-10-31
!
! ABSTRACT: READ A GRIB FILE AND RETURN ITS INDEX CONTENTS.
!   SEE SUBPROGRAM IXGB FOR DOCUMENTATION OF THE INDEX BUFFER STRUCTURE.
!
! PROGRAM HISTORY LOG:
!   95-10-31  IREDELL
!
! USAGE:    CALL GETGIR(LUGB,MSK1,MSK2,MBUF,CBUF,NLEN,NNUM,IRET)
!   INPUT ARGUMENTS:
!     LUGB         INTEGER UNIT OF THE UNBLOCKED GRIB FILE
!     MSK1         INTEGER NUMBER OF BYTES TO SEARCH FOR FIRST MESSAGE
!     MSK2         INTEGER NUMBER OF BYTES TO SEARCH FOR OTHER MESSAGES
!     MNUM         INTEGER NUMBER OF INDEX RECORDS TO SKIP (USUALLY 0)
!     MBUF         INTEGER LENGTH OF CBUF IN BYTES
!   OUTPUT ARGUMENTS:
!     CBUF         CHARACTER*1 (MBUF) BUFFER TO RECEIVE INDEX DATA
!     NLEN         INTEGER LENGTH OF EACH INDEX RECORD IN BYTES
!     NNUM         INTEGER NUMBER OF INDEX RECORDS
!                  (=0 IF NO GRIB MESSAGES ARE FOUND)
!     IRET         INTEGER RETURN CODE
!                    0      ALL OK
!                    1      CBUF TOO SMALL TO HOLD INDEX DATA
!
! SUBPROGRAMS CALLED:
!   SKGB           SEEK NEXT GRIB MESSAGE
!   IXGB           MAKE INDEX RECORD
!
! REMARKS: SUBPROGRAM CAN BE CALLED FROM A MULTIPROCESSING ENVIRONMENT.
!   DO NOT ENGAGE THE SAME LOGICAL UNIT FROM MORE THAN ONE PROCESSOR.
!
! ATTRIBUTES:
!   LANGUAGE: FORTRAN 77
!   MACHINE:  CRAY, WORKSTATIONS
!
!$$$
   CHARACTER CBUF(MBUF)
   PARAMETER(LINDEX=152)
   !
   !  SEARCH FOR FIRST GRIB MESSAGE
   !
   ISEEK=0
   CALL SKGB(LUGB,ISEEK,MSK1,LSKIP,LGRIB)
   DO M=1,MNUM
     IF(LGRIB.GT.0) THEN
       ISEEK=LSKIP+LGRIB
       CALL SKGB(LUGB,ISEEK,MSK2,LSKIP,LGRIB)
     ENDIF
   ENDDO
   !
   !  MAKE AN INDEX RECORD FOR EVERY GRIB RECORD FOUND
   !
   NLEN=LINDEX
   NNUM=0
   IRET=0
   DO WHILE(IRET.EQ.0.AND.LGRIB.GT.0)
     IF(NLEN*(NNUM+1).LE.MBUF) THEN
       NNUM=NNUM+1
       CALL IXGB(LUGB,LSKIP,LGRIB,NLEN,NNUM,CBUF)
       ISEEK=LSKIP+LGRIB
       CALL SKGB(LUGB,ISEEK,MSK2,LSKIP,LGRIB)
     ELSE
       IRET=1
     ENDIF
   ENDDO
   
   RETURN
   END
