    FUNCTION IW3JDN(IYEAR,MONTH,IDAY)
!$$$   SUBPROGRAM  DOCUMENTATION  BLOCK
!
! SUBPROGRAM: IW3JDN         COMPUTE JULIAN DAY NUMBER
!   AUTHOR: JONES,R.E.       ORG: W342       DATE: 90-06-04
!
! ABSTRACT: COMPUTES JULIAN DAY NUMBER FROM YEAR (4 DIGITS), MONTH,
!   AND DAY. IW3JDN IS VALID FOR YEARS 1583 A.D. TO 3300 A.D.
!   JULIAN DAY NUMBER CAN BE USED TO COMPUTE DAY OF WEEK, DAY OF
!   YEAR, RECORD NUMBERS IN AN ARCHIVE, REPLACE DAY OF CENTURY,
!   FIND THE NUMBER OF DAYS BETWEEN TWO DATES.
!
! PROGRAM HISTORY LOG:
!   87-01-16  R.E.JONES
!   89-02-02  R.E.JONES   CHANGE TO MICROSOFT FORTRAN 4.10
!   90-06-04  R.E.JONES   CHANGE TO SUN FORTRAN 1.3
!   91-03-29  R.E.JONES   CONVERT TO Silicon Graphics FORTRAN
!   93-03-29  R.E.JONES   ADD SAVE STATEMENT
!
! USAGE:   II = IW3JDN(IYEAR,MONTH,IDAY)
!
!   INPUT VARIABLES:
!     NAMES  INTERFACE DESCRIPTION OF VARIABLES AND TYPES
!     ------ --------- -----------------------------------------------
!     IYEAR  ARG LIST  INTEGER*4 YEAR           ( 4 DIGITS)
!     MONTH  ARG LIST  INTEGER*4 MONTH OF YEAR   (1 - 12)
!     IDAY   ARG LIST  INTEGER*4 DAY OF MONTH    (1 - 31)
!
!   OUTPUT VARIABLES:
!     NAMES  INTERFACE DESCRIPTION OF VARIABLES AND TYPES
!     ------ --------- -----------------------------------------------
!     IW3JDN FUNTION   INTEGER*4 JULIAN DAY NUMBER
!                      JAN. 1,1960 IS JULIAN DAY NUMBER 2436935
!                      JAN. 1,1987 IS JULIAN DAY NUMBER 2446797
!
!   REMARKS: JULIAN PERIOD WAS DEVISED BY JOSEPH SCALIGER IN 1582.
!     JULIAN DAY NUMBER #1 STARTED ON JAN. 1,4713 B.C. THREE MAJOR
!     CHRONOLOGICAL CYCLES BEGIN ON THE SAME DAY. A 28-YEAR SOLAR
!     CYCLE, A 19-YEAR LUNER CYCLE, A 15-YEAR INDICTION CYCLE, USED
!     IN ANCIENT ROME TO REGULATE TAXES. IT WILL TAKE 7980 YEARS
!     TO COMPLETE THE PERIOD, THE PRODUCT OF 28, 19, AND 15.
!     SCALIGER NAMED THE PERIOD, DATE, AND NUMBER AFTER HIS FATHER
!     JULIUS (NOT AFTER THE JULIAN CALENDAR). THIS SEEMS TO HAVE
!     CAUSED A LOT OF CONFUSION IN TEXT BOOKS. SCALIGER NAME IS
!     SPELLED THREE DIFFERENT WAYS. JULIAN DATE AND JULIAN DAY
!     NUMBER ARE INTERCHANGED. A JULIAN DATE IS USED BY ASTRONOMERS
!     TO COMPUTE ACCURATE TIME, IT HAS A FRACTION. WHEN TRUNCATED TO
!     AN INTEGER IT IS CALLED AN JULIAN DAY NUMBER. THIS FUNCTION
!     WAS IN A LETTER TO THE EDITOR OF THE COMMUNICATIONS OF THE ACM
!     VOLUME 11 / NUMBER 10 / OCTOBER 1968. THE JULIAN DAY NUMBER
!     CAN BE CONVERTED TO A YEAR, MONTH, DAY, DAY OF WEEK, DAY OF
!     YEAR BY CALLING SUBROUTINE W3FS26.
!
! ATTRIBUTES:
!   LANGUAGE: SiliconGraphics 3.5 FORTRAN 77
!   MACHINE:  SiliconGraphic IRIS-4D/25, 35, INDIGO
!
!$$$

    SAVE

    IW3JDN  =    IDAY - 32075                                                  &
               + 1461 * (IYEAR + 4800 + (MONTH - 14) / 12) / 4                 &
               + 367 * (MONTH - 2 - (MONTH -14) / 12 * 12) / 12                &
               - 3 * ((IYEAR + 4900 + (MONTH - 14) / 12) / 100) / 4
    RETURN
    END
