!-----------------------------------------------------------------------
   SUBROUTINE SKGB(LUGB,ISEEK,MSEEK,LSKIP,LGRIB)
!$$$  SUBPROGRAM DOCUMENTATION BLOCK
!
! SUBPROGRAM: SKGB           SEARCH FOR NEXT GRIB MESSAGE
!   PRGMMR: IREDELL          ORG: W/NMC23     DATE: 93-11-22
!
! ABSTRACT: THIS SUBPROGRAM SEARCHES A FILE FOR THE NEXT GRIB 1 MESSAGE.
!   A GRIB 1 MESSAGE IS IDENTIFIED BY ITS INDICATOR SECTION, I.E.
!   AN 8-BYTE SEQUENCE WITH 'GRIB' IN BYTES 1-4 AND 1 IN BYTE 8.
!   IF FOUND, THE LENGTH OF THE MESSAGE IS DECODED FROM BYTES 5-7.
!   THE SEARCH IS DONE OVER A GIVEN SECTION OF THE FILE.
!   THE SEARCH IS TERMINATED IF AN EOF OR I/O ERROR IS ENCOUNTERED.
!
! PROGRAM HISTORY LOG:
!   93-11-22  IREDELL
!   95-10-31  IREDELL   ADD CALL TO BAREAD 
!   97-03-14  IREDELL   CHECK FOR '7777'
!
! USAGE:    CALL SKGB(LUGB,ISEEK,MSEEK,LSKIP,LGRIB)
!   INPUT ARGUMENTS:
!     LUGB         INTEGER LOGICAL UNIT OF INPUT GRIB FILE
!     ISEEK        INTEGER NUMBER OF BYTES TO SKIP BEFORE SEARCH
!     MSEEK        INTEGER MAXIMUM NUMBER OF BYTES TO SEARCH
!   OUTPUT ARGUMENTS:
!     LSKIP        INTEGER NUMBER OF BYTES TO SKIP BEFORE MESSAGE
!     LGRIB        INTEGER NUMBER OF BYTES IN MESSAGE (0 IF NOT FOUND)
!
! SUBPROGRAMS CALLED:
!   BAREAD       BYTE-ADDRESSABLE READ
!   GBYTE        GET INTEGER DATA FROM BYTES
!
! ATTRIBUTES:
!   LANGUAGE: FORTRAN
!
!$$$
   INTEGER, PARAMETER  ::  LSEEK=128
   CHARACTER           ::  Z(LSEEK)
   CHARACTER           ::  Z4(4)
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   LGRIB=0
   KS=ISEEK
   KN=MIN(LSEEK,MSEEK)
   KZ=LSEEK

   !
   ! LOOP UNTIL GRIB MESSAGE IS FOUND
   !
   DO WHILE(LGRIB.EQ.0.AND.KN.GE.8.AND.KZ.EQ.LSEEK)
      !
      ! READ PARTIAL SECTION
      !
      CALL BAREAD(LUGB,KS,KN,KZ,Z)
      KM=KZ-8+1
      K=0
      !
      ! LOOK FOR 'GRIB...1' IN PARTIAL SECTION
      !
      DO WHILE(LGRIB.EQ.0.AND.K.LT.KM)
         CALL GBYTE(Z,I4,(K+0)*8,4*8)
         CALL GBYTE(Z,I1,(K+7)*8,1*8)
         IF(I4.EQ.1196575042.AND.I1.EQ.1) THEN
            !
            ! LOOK FOR '7777' AT END OF GRIB MESSAGE
            !
            CALL GBYTE(Z,KG,(K+4)*8,3*8)
            CALL BAREAD(LUGB,KS+K+KG-4,4,K4,Z4)
            IF(K4.EQ.4) THEN
               CALL GBYTE(Z4,I4,0,4*8)
               IF(I4.EQ.926365495) THEN
                  !
                  ! GRIB MESSAGE FOUND
                  !
                  LSKIP=KS+K
                  LGRIB=KG
               ENDIF
            ENDIF
         ENDIF
         K=K+1
      ENDDO
      KS=KS+KM
      KN=MIN(LSEEK,ISEEK+MSEEK-KS)
   ENDDO
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   RETURN
   END
