    SUBROUTINE W3TAGB(PROG,KYR,JD,LF,ORG)
!$$$   SUBPROGRAM DOCUMENTATION BLOCK
!
! SUBPROGRAM: W3TAGB        OPERATIONAL JOB IDENTIFIER
!   PRGMMR: FARLEY          ORG: NP11          DATE: 1998-03-17
!
! ABSTRACT: PRINTS IDENTIFYING INFORMATION FOR OPERATIONAL
!   codes. CALLED AT THE BEGINNING OF A code, W3TAGB PRINTS
!   THE program NAME, THE YEAR AND JULIAN DAY OF ITS
!   COMPILATION, AND THE RESPONSIBLE ORGANIZATION. ON A 2ND
!   LINE IT PRINTS THE STARTING DATE-TIME. CALLED AT THE
!   END OF A JOB, entry routine, W3TAGE PRINTS A LINE WITH THE
!   ENDING DATE-TIME AND A 2ND LINE STATING THE program name 
!   AND THAT IT HAS ENDED.
!
! PROGRAM HISTORY LOG:
!   85-10-29  J.NEWELL
!   89-10-20  R.E.JONES   CONVERT TO CRAY CFT77 FORTRAN
!   91-03-01  R.E.JONES   ADD MACHINE NAME TO ENDING LINE
!   92-12-02  R.E.JONES   ADD START-ENDING TIME-DATE
!   93-11-16  R.E.JONES   ADD DAY OF YEAR, DAY OF WEEK, AND JULIAN DAY
!                         NUMBER. 
!   97-12-24  M.FARLEY    PRINT STATEMENTS MODIFIED FOR 4-DIGIT YR 
!   98-03-17  M.FARLEY    REPLACED DATIMX WITH CALLS TO W3LOCDAT/W3DOXDAT 
!   99-01-29  B. VUONG    CONVERTED TO IBM RS/6000 SP
!
!   99-06-17  A. Spruill  ADJUSTED THE SIZE OF PROGRAM NAME TO ACCOMMODATE
!                         THE 20 CHARACTER NAME CONVENTION ON THE IBM SP.
! 1999-08-24  Gilbert     added call to START() in W3TAGB and a call
!                         to SUMMARY() in W3TAGE to print out a 
!                         resource summary list for the program using
!                         W3TAGs.
!
! USAGE:  CALL W3TAGB(PROG, KYR, JD, LF, ORG)
!         CALL W3TAGE(PROG)
!
!   INPUT VARIABLES:
!     NAMES  INTERFACE DESCRIPTION OF VARIABLES AND TYPES
!     ------ --------- -----------------------------------------------
!     PROG   ARG LIST  PROGRAM NAME   CHARACTER*1
!     KYR    ARG LIST  YEAR OF COMPILATION   INTEGER
!     JD     ARG LIST  JULIAN DAY OF COMPILATION   INTEGER
!     LF     ARG LIST  HUNDRETHS OF JULIAN DAY OF COMPILATION
!                      INTEGER     (RANGE IS 0 TO 99 INCLUSIVE)
!     ORG    ARG LIST  ORGANIZATION CODE (SUCH AS WD42)
!                      CHARACTER*1
!
!   OUTPUT VARIABLES:
!     NAMES  INTERFACE DESCRIPTION OF VARIABLES AND TYPES
!     ----------------------------------------------------------------
!     DDATE  PRINT     YEAR AND JULIAN DAY (NEAREST HUNDRETH)
!            FILE      OF COMPILATION  REAL
!
!   SUBPROGRAMS CALLED: CLOCK, DATE
!
!   REMARKS: FULL WORD USED IN ORDER TO HAVE AT LEAST
!            SEVEN DECIMAL DIGITS ACCURACY FOR VALUE OF DDATE.
!            SUBPROGRAM CLOCK AND DATE MAY DIFFER FOR EACH TYPE
!            COMPUTER. YOU MAY HAVE TO CHANGE THEM FOR ANOTHER
!            TYPE OF COMPUTER.
!
! ATTRIBUTES:
!   LANGUAGE: FORTRAN 90
!
!$$$
!
      CHARACTER *(*)    ::  PROG,ORG
      CHARACTER(len=3)  ::  JMON(12)
      CHARACTER(len=3)  ::  DAYW(7)
!
      INTEGER           ::  IDAT(8), JDOW, JDOY, JDAY
!
      SAVE
!
      DATA  DAYW/'SUN','MON','TUE','WEN','THU','FRI','SAT'/
      DATA  JMON  /'JAN','FEB','MAR','APR','MAY','JUN',                        &
                   'JUL','AUG','SEP','OCT','NOV','DEC'/
! 
      CALL START()

      DYR   = KYR
      DYR   = 1.0E+03 * DYR
      DJD   = JD
      DLF   = LF
      DLF   = 1.0E-02 * DLF
      DDATE = DYR + DJD + DLF
      PRINT 600
  600    FORMAT(//,10('* . * . '))
      PRINT 601, PROG, DDATE, ORG
  601    FORMAT(5X,'PROGRAM ',A,' HAS BEGUN. COMPILED ',F10.2,                 &
      5X, 'ORG: ',A)
!
      CALL W3LOCDAT(IDAT)
      CALL W3DOXDAT(IDAT,JDOW,JDOY,JDAY)
      PRINT 602, JMON(IDAT(2)),IDAT(3),IDAT(1),IDAT(5),IDAT(6),                &
      IDAT(7),IDAT(8),JDOY,DAYW(JDOW),JDAY
  602    FORMAT(5X,'STARTING DATE-TIME  ',A3,1X,I2.2,',',                      &
      I4.4,2X,2(I2.2,':'),I2.2,'.',I3.3,2X,I3,2X,A3,2X,I8,//)
      RETURN
!
      ENTRY W3TAGE(PROG)
!
      CALL W3LOCDAT(IDAT)
      CALL W3DOXDAT(IDAT,JDOW,JDOY,JDAY)
      PRINT 603, JMON(IDAT(2)),IDAT(3),IDAT(1),IDAT(5),IDAT(6),                &
      IDAT(7),IDAT(8),JDOY,DAYW(JDOW),JDAY
  603    FORMAT(//,5X,'ENDING DATE-TIME    ',A3,1X,I2.2,',',                   &
      I4.4,2X,2(I2.2,':'),I2.2,'.',I3.3,2X,I3,2X,A3,2X,I8)
      PRINT 604, PROG
  604    FORMAT(5X,'PROGRAM ',A,' HAS ENDED.  IBM RS/6000 SP')
! 604    FORMAT(5X,'PROGRAM ',A,' HAS ENDED.  CRAY J916/2048')
! 604    FORMAT(5X,'PROGRAM ',A,' HAS ENDED.  CRAY Y-MP EL2/256')
      PRINT 605
  605    FORMAT(10('* . * . '))

      CALL SUMMARY()
!
      RETURN
      END
