    SUBROUTINE W3FI04(IENDN,ITYPEC,LW)
!$$$   SUBPROGRAM  DOCUMENTATION  BLOCK
!
! SUBPROGRAM: W3FI04         FIND WORD SIZE, ENDIAN, CHARACTER SET
!   PRGMNR: JONES,R.E.       ORG: W/NMC42       DATE: 94-10-07
!
! ABSTRACT: SUBROUTINE COMPUTES WORD SIZE, THE TYPE OF CHARACTER
!   SET, ASCII OR EBCDIC, AND IF THE COMPUTER IS BIG-ENDIAN, OR
!   LITTLE-ENDIAN.
!
! PROGRAM HISTORY LOG:
!   94-10-07  R.E.JONES
!
! USAGE:  CALL W3FI04 (IENDN, ITYPEC, LW)
!
!   OUTPUT ARGUMENT LIST:
!     IENDN     -  INTEGER FOR BIG-ENDIAN OR LITTLE-ENDIAN
!                  = 0   BIG-ENDIAN
!                  = 1   LITTLE-ENDIAN
!                  = 2   CANNOT COMPUTE
!     ITYPEC    -  INTEGER FOR TYPE OF CHARACTER SET
!                  = 0   ASCII  CHARACTER SET
!                  = 1   EBCDIC CHARACTER SET
!                  = 2   NOT ASCII OR EBCDIC
!     LW        -  INTEGER FOR WORDS SIZE OF COMPUTER IN BYTES 
!                  = 4   FOR 32 BIT COMPUTERS
!                  = 8   FOR 64 BIT COMPUTERS  
!
! REMARKS: BASED ON EXAMPLE IN DR. DOBB'S JOURNAL NOV. 1994
!   Endian-Neutral Software, Part 2, James R. Gillig Page 44-51.
!   Example 1 coded in C on page 46.
!
! ATTRIBUTES:
!   LANGUAGE: SiliconGraphics 3.5 FORTRAN 77
!   MACHINE:  SiliconGraphics IRIS-4D/25, 35, INDIGO, INDY
!
!$$$

   CHARACTER(len=8)  ::  CTEST1
   CHARACTER(len=8)  ::  CTEST2
   CHARACTER(len=1)  ::  CTEST3(8)
   CHARACTER(len=1)  ::  BLANK
   INTEGER           ::  ITEST1
   INTEGER           ::  ITEST2
   INTEGER           ::  ITEST3
   INTEGER           ::  IENDN
   INTEGER           ::  ITYPEC
   INTEGER           ::  LW

   EQUIVALENCE   (CTEST1,ITEST1),(CTEST2,ITEST2)

   EQUIVALENCE   (ITEST3,CTEST3(1))

   DATA  CTEST1/'12345678'/
   DATA  ITEST3/Z'01020304'/
   DATA  BLANK /' '/

   SAVE
   
   !
   ! TEST FOR TYPE OF CHARACTER SET
   ! BLANK IS 32 (20 HEX) IN ASCII, 64 (40 HEX) IN EBCDEC
   !
   IF (ICHAR(BLANK).EQ.32) THEN
      ITYPEC = 0
   ELSE IF (ICHAR(BLANK).EQ.64) THEN
      !
      ! COMPUTER IS PROBABLY AN IBM360, 370, OR 390 WITH
      ! A 32 BIT WORD SIZE, AND BIG-ENDIAN.
      !
     ITYPEC = 1
   ELSE
     ITYPEC = 2
   END IF
   !
   ! TEST FOR WORD SIZE, SET LW TO 4 FOR 32 BIT COMPUTER,
   ! 8 FOR FOR 64 BIT COMPUTERS
   !
   ITEST2 = ITEST1
   IF (CTEST1 .EQ. CTEST2) THEN
      !
      ! COMPUTER MAY BE A CRAY, OR COULD BE DEC VAX ALPHA
      ! OR SGI WITH R4000, R4400, R8000, R10000. THIS WILL
      ! RETURN 8 ON DEC ALPHA AND SGI USING -i8 f77 FORTRAN
      ! COMPILER OPTION.
      !
      LW = 8
   ELSE
     LW = 4
   ENDIF
   ! 
   !  USING ITEST3 WITH Z'01020304' EQUIVALNCED TO CTEST3
   !  ON A 32 BIT BIG-ENDIAN COMPUTER 03 IS IN THE 3RD 
   !  BYTE OF A 4 BYTE WORD. ON A 32 BIT LITTLE-ENDIAN 
   !  COMPUTER IT IS IN 2ND BYTE.
   !  ON A 64 BIT COMPUTER Z'01020304' IS RIGHT ADJUSTED IN
   !  A 64 BIT WORD, 03 IS IN THE 7TH BYTE.  ON A LITTLE-
   !  ENDIAN 64 BIT COMPUTER IT IS IN THE 2ND BYTE.
   ! 
   IF (LW.EQ.4) THEN           
      IF (ICHAR(CTEST3(3)).EQ.3) THEN
         IENDN = 0
      ELSE IF (ICHAR(CTEST3(3)).EQ.2) THEN 
         IENDN = 1
      ELSE
         IENDN = 2
      END IF
   ELSE IF (LW.EQ.8) THEN           
      IF (ICHAR(CTEST3(7)).EQ.3) THEN
         IENDN = 0
      ELSE IF (ICHAR(CTEST3(2)).EQ.3) THEN
         IENDN = 1
      ELSE
       IENDN = 2
      END IF
   ELSE
      IENDN = 2
   END IF

   RETURN
   END
