      SUBROUTINE XMOVEX(COUT,CIN,MBYTES)
C     SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    XMOVEX      MOVES FIELD FROM ONE ARRAY TO ANOTHER
C   PRGMMR: KEYSER           ORG: W/NMC22    DATE: 07-02-92
C
C ABSTRACT: MOVES "MBYTES" BYTES OF DATA INTO ARRAY "COUT" FROM
C   ARRAY "CIN".  THE FORTRAN TYPING OF "COUT" AND "CIN" IS NOT
C   SIGNIFICANT.  "MBYTES" MUST BE .GT. ZERO AND THE FIELDS SHOULD
C   NOT UNINTENTIONALLY OVERLAP.  (MOVING IS ACCOMPLISHED WITH A
C   DO LOOP.)
C
C PROGRAM HISTORY LOG:
C   92-07-02  D. A. KEYSER (W/NMC22)
C   92-11-24  R.E.JONES   REPLACE FORTRAN DO LOOP WITH XMOVEX WHICH
C                         USES CRAY UTILITY STRMOV FOR MORE SPEED.
C
C USAGE:    CALL XMOVEX(COUT,CIN,MBYTES)
C   INPUT ARGUMENT LIST:
C     CIN      - STARTING ADDRESS OF DATA TO BE MOVED INTO "COUT"
C     MBYTES   - NUMBER OF BYTES TO MOVE FROM "CIN" TO "COUT"
C
C   OUTPUT ARGUMENT LIST:      (INCLUDING WORK ARRAYS)
C     COUT     - STARTING ADDRESS OF DATA MOVED FROM "CIN"
C
C SUBPROGRAM CALLED:
C   SYSTEM LIBRARY: GETB1, STRMOV
C
C REMARKS: THE VERSION OF THIS SUBROUTINE ON THE NAS COMMON LIBRARY
C   IS NAS-SPECIFIC SUBR. WRITTEN IN ASSEMBLY LANG. TO ALLOW FAST
C   COMPUTATION TIME.  SUBR. PLACED IN CRAY W3LIB TO ALLOW CODES TO
C   COMPILE ON BOTH THE NAS AND CRAY MACHINES. A FORTRAN DO LOOP
C   MOVES CHARACTERS AT A RATE OF 2.5 MILLION PER SECOND ON A CRAY,
C   STRMOV MOVES CHARACTER DATA AT A RATE OF OVER 600 MILLION PER SEC.
C
C ATTRIBUTES:
C   LANGUAGE: CRAY CFT77 FORTRAN
C   MACHINE:  CRAY C916-128, CRAY Y-MP8/864, CRAY Y-MP EL2/256
C
C
      CHARACTER*1  COUT(*),CIN(*)
C
      INTEGER      CHRIN
      INTEGER      CHROUT
      INTEGER      GETB1
      INTEGER      PARM(4)
C
      POINTER      (PPARM,PARM)
C
      SAVE
C
C     DO 1000  I = 1,MBYTES
C        COUT(I) = CIN(I)
C1000 CONTINUE
C
C     USE GETB1 TO GET LIST OF ADDRESS'S OF PARAMETERS
C     GETB1 IS A CRAY UTILITY
C
      PPARM   = GETB1()
C
C     BITS 63-58 OF THE ADDRESS HAVE THE BIT OFFSET IN THE WORD
C     (WHERE CHARACTER DATA STARTS). THIS IS DIVIDED BY 8 AND
C     1 ADDED FOR STARTING CHARACTER IN A WORD, SHOULD BE 1 TO 8.
C
      CHRIN  = ISHFT(PARM(3),-61) + 1
      CHROUT = ISHFT(PARM(2),-61) + 1
C
      CALL STRMOV(CIN, CHRIN, MBYTES, COUT, CHROUT)
C
      RETURN
      END
