!-----------------------------------------------------------------------
   SUBROUTINE BAREAD(LU,IB,NB,KA,A)
!$$$  SUBPROGRAM DOCUMENTATION BLOCK
!
! SUBPROGRAM: BAREAD         BYTE-ADDRESSABLE READ
!   PRGMMR: IREDELL          ORG: W/NMC23     DATE: 94-04-01
!
! ABSTRACT: READ A GIVEN NUMBER OF BYTES FROM AN UNBLOCKED FILE,
!   SKIPPING A GIVEN NUMBER OF BYTES.
!
! PROGRAM HISTORY LOG:
!   94-04-01  IREDELL
!   95-10-16  IREDELL     WORKSTATION VERSION
!
! USAGE:    CALL BAREAD(LU,IB,NB,KA,A)
!   INPUT ARGUMENTS:
!     LU           INTEGER UNIT TO READ
!     IB           INTEGER NUMBER OF BYTES TO SKIP
!     NB           INTEGER NUMBER OF BYTES TO READ
!   OUTPUT ARGUMENTS:
!     KA           INTEGER NUMBER OF BYTES ACTUALLY READ
!     A            CHARACTER*1 (NB) BUFFER READ
!
! SUBPROGRAMS CALLED:
!   FSEEK        SET FILE POSITION
!   FGETC        READ BYTE FROM FILE
!
! ATTRIBUTES:
!   LANGUAGE: FORTRAN 77
!   MACHINE: WORKSTATIONS
!
!$$$
   CHARACTER  ::  A(NB)
   INTEGER    ::  FSEEK,FGETC
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   IF(FSEEK(LU,IB,0).EQ.0) THEN
     KA=0
     DO WHILE(KA.LT.NB.AND.FGETC(LU,A(KA+1)).EQ.0)
       KA=KA+1
     ENDDO
   ENDIF
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   RETURN
   END
