   SUBROUTINE W3FI01(LW)
!$$$  SUBPROGRAM DOCUMENTATION BLOCK
!                .      .    .                                       .
! SUBPROGRAM:  W3FI01        DETERMINES MACHINE WORD LENGTH IN BYTES
!   PRGMMR: KEYSER           ORG: NMC22       DATE:92-07-30
!
! ABSTRACT: DETERMINES THE NUMBER OF BYTES IN A FULL WORD FOR THE
!   PARTICULAR MACHINE (IBM, CRAY, WORKSTATION, PC).
!
! PROGRAM HISTORY LOG:
!   92-01-10  R. KISTLER (W/NMC23)
!   92-05-22  D. A. KEYSER -- DOCBLOCKED/COMMENTED
!   93-03-29  R.E.JONES    -- ADD SAVE STATEMENT
!
! USAGE:    CALL W3FI01(LW)
!   OUTPUT ARGUMENT LIST:      (INCLUDING WORK ARRAYS)
!     LW       - MACHINE WORD LENGTH IN BYTES
!
!   OUTPUT FILES:
!     FT06F001 - PRINTOUT
!
! REMARKS: NONE.
!
! ATTRIBUTES:
!   LANGUAGE: SliconGraphics 3.5 FORTRAN 77
!   MACHINE:  SliconGraphics IRIS-4D/25, 35, INDIGO
!
!$$$

   CHARACTER(len=4)  ::  CPRINT(2)
   CHARACTER(len=8)  ::  CTEST1,CTEST2
   INTEGER           ::  ITEST1,ITEST2

   EQUIVALENCE (CTEST1,ITEST1),(CTEST2,ITEST2)

   SAVE

   DATA  CTEST1/'12345678'/

   ITEST2 = ITEST1
   ! PRINT *,' CTEST1 = ',CTEST1,' CTEST2 = ',CTEST2
   IF (CTEST1 .EQ. CTEST2) THEN
      ! PRINT*,' MACHINE WORD LENGTH IS 8 BYTES'
      LW = 8
   ELSE
      ! PRINT*,' MACHINE WORD LENGTH IS 4 BYTES'
      LW = 4
   ENDIF
   RETURN
   END
