   SUBROUTINE XMOVEX(OUT,IN,IBYTES)
!
!      THIS SUBROUTINE MAY NOT BE NEEDED, ITS WAS IN
!      ASSEMBLER LANGUAGE TO MOVE DATA, IT RAN ABOUT THREE
!      TIMES FASTER THAN A FORTRAN DO LOOP, IT WAS USED TO
!      MAKE SURE THE DATA TO BE UNPACKED WAS ON A WORD BOUNDARY,
!      THIS MAY NOT BE NEEDED ON SOME BRANDS OF COMPUTERS.
!
   CHARACTER(len=1)  ::  OUT(*)
   CHARACTER(len=1)  ::  IN(*)
   INTEGER           ::  IBYTES

   SAVE

   DO I = 1,IBYTES
     OUT(I) = IN(I)
   END DO

   RETURN
   END
