   SUBROUTINE UNPINDX(CBUF,NLEN,NNUM,KPDS,KGDS,LSKIP,LGRIB,IRET)
!$$$  SUBPROGRAM DOCUMENTATION BLOCK
!
! SUBPROGRAM: UNPINDX        UNPACKS GRIB INDEX BUFFER CONTENTS 
!   PRGMMR: IREDELL          ORG: W/NMC23     DATE: 95-12-13
!     MODIFIED BY KANAMITSU
!
! ABSTRACT: UNPACKS A GRIB INDEX BUFFER.
!
! PROGRAM HISTORY LOG:
!   95-12-13  KANAMITSU
!
! USAGE:    CALL UNPINDX(CBUF,NLEN,NNUM,KPDS,KGDS,LSKIP,LGRIB,IRET)
!   INPUT ARGUMENTS:
!     CBUF         CHARACTER*1 (NLEN*NNUM) BUFFER CONTAINING INDEX DATA
!     NLEN         INTEGER LENGTH OF EACH INDEX RECORD IN BYTES
!     NNUM         INTEGER NUMBER OF INDEX RECORDS
!   OUTPUT ARGUMENTS:
!     KPDS         INTEGER (25) UNPACKED PDS PARAMETERS
!     KGDS         INTEGER (22) UNPACKED GDS PARAMETERS
!     LSKIP        INTEGER NUMBER OF BYTES TO SKIP
!     LGRIB        INTEGER NUMBER OF BYTES TO READ
!     IRET         INTEGER RETURN CODE
!                    0      ALL OK
!                    1      REQUEST NOT FOUND
!
! REMARKS: SUBPROGRAM CAN BE CALLED FROM A MULTIPROCESSING ENVIRONMENT.
!   THIS SUBPROGRAM IS INTENDED FOR PRIVATE USE BY GETGB ROUTINES ONLY.
!
! SUBPROGRAMS CALLED:
!   GBYTE          UNPACK BYTES
!   FI632          UNPACK PDS
!   FI633          UNPACK GDS
!
! ATTRIBUTES:
!   LANGUAGE: FORTRAN 77
!   MACHINE:  CRAY, WORKSTATIONS
!
!$$$
   CHARACTER(len=1)    ::  CBUF(NLEN*NNUM)
   CHARACTER           ::  CPDS(80)*1,CGDS(80)*1
   DIMENSION           ::  LSKIP(NNUM),LGRIB(NNUM)
   INTEGER             ::  KPDS(25,NNUM),KGDS(22,NNUM)
   INTEGER             ::  KPTR(16)

   !
   !  Loop for NNUM
   !
   DO K=1,NNUM
      !
      !  PDS
      !
      DO I=1,36
         CPDS(I)=CBUF((K-1)*NLEN+25+I)
      ENDDO
      DO I=1,16
         KPTR(I)=0
      ENDDO
      CALL GBYTE(CBUF,KPTR(3),(K-1)*NLEN*8+25*8,3*8)
      KPDS(18,K)=1
      CALL GBYTE(CPDS,KPDS(4,K),7*8,8)
      CALL FI632(CPDS,KPTR,KPDS(1,K),IRET)
      !
      !  GDS
      !
      DO I=1,42
         CGDS(I)=CBUF((K-1)*NLEN+53+I)
      ENDDO
      DO I=1,16
         KPTR(I)=0
      ENDDO
      CALL FI633(CGDS,KPTR,KGDS(1,K),IRET)
      !
      ! LSKIP and NLEN
      !
      CALL GBYTE(CBUF,LSKIP(K),(K-1)*NLEN*8,4*8)
      CALL GBYTE(CBUF,LGRIB(K),(K-1)*NLEN*8+20*8,4*8)

   ENDDO

   RETURN
   END
