   subroutine idsdef(iptv,ids)                                               
!                                                                               
! abstract: sets decimal scalings defaults for various parameters.              
!   a decimal scaling of -3 means data is packed in kilo-si units.              
!                                                                               
! program history log:                                                          
!   92-10-31  iredell             development                                              
!   00-01-31  song-you hong       add other hydrometeros etc                                                   
!                                                                               
! usage:    call idsdef(iptv,ids)                                               
!   input arguments:                                                            
!     iptv         paramter table version (only 1 or 2 is recognized)           
!   output arguments:                                                           
!     ids          integer (255) decimal scalings                               
!                  (unknown decimal scalings will not be set)                   
!                                                                               
   integer  ::  ids(255)                                                        
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -         
   do k=1,255
      ids(k)=0
   enddo

   if(iptv.eq.1.or.iptv.eq.2) then                                           
      ids(001)=0      ! pressure (pa)                                         
      ids(002)=0      ! sea-level pressure (pa)                               
      ids(003)=4      ! pressure tendency (pa/s)                              
                      !                                                       
                      !                                                       
      ids(006)=0      ! geopotential (m2/s2)                                   
      ids(007)=1      ! geopotential height (m)                               
      ids(008)=1      ! geometric height (m)                                  
      ids(009)=1      ! standard deviation of height (m)                      
                      !                                                       
      ids(011)=2      ! temperature (k)                                       
      ids(012)=2      ! virtual temperature (k)                               
      ids(013)=2      ! potential temperature (k)                             
      ids(014)=2      ! pseudo-adiabatic potential temperature (k)            
      ids(015)=2      ! maximum temperature (k)                               
      ids(016)=2      ! minimum temperature (k)                               
      ids(017)=2      ! dewpoint temperature (k)                              
      ids(018)=2      ! dewpoint depression (k)                               
      ids(019)=5      ! temperature lapse rate (k/m)                          
      ids(020)=0      ! visibility (m)                                        
                      !                                                       
      ids(021)=5      ! river storage (log10,mm)
      ids(022)=5      ! river discharge (log10,kg/s)
      ids(023)=0      ! river direction (0-9)
      ids(024)=8      ! total runoff to river channel (kg/m2/s)
                      !
      ids(025)=2      ! temperature anomaly (k)                               
      ids(026)=0      ! pressure anomaly (pa)                                 
      ids(027)=1      ! geopotential height anomaly (m)                       
                      ! wave spectra 1 ()                                     
                      ! wave spectra 2 ()                                     
                      ! wave spectra 3 ()                                     
      ids(031)=1      ! wind direction (degrees)                              
      ids(032)=2      ! wind speed (m/s)                                      
      ids(033)=2      ! zonal wind (m/s)                                      
      ids(034)=2      ! meridional wind (m/s)                                 
      ids(035)=-4     ! streamfunction (m2/s)                                 
      ids(036)=-4     ! velocity potential (m2/s)                             
      ids(037)=0      ! montgomery stream function (m2/s2)                    
      ids(038)=9      ! sigma vertical velocity (1/s)                         
      ids(039)=4      ! pressure vertical velocity (pa/s)                     
      ids(040)=5      ! geometric vertical velocity (m/s)                     
      ids(041)=7      ! absolute vorticity (1/s)                              
      ids(042)=7      ! absolute divergence (1/s)                             
      ids(043)=7      ! relative vorticity (1/s)                              
      ids(044)=7      ! relative divergence (1/s)                             
      ids(045)=5      ! vertical u shear (1/s)                                
      ids(046)=5      ! vertical v shear (1/s)                                
      ids(047)=0      ! direction of current (degrees)                        
                      ! speed of current (m/s)                                
                      ! u of current (m/s)                                    
                      ! v of current (m/s)                                    
!      ids(051)=6      ! specific humidity (kg/kg)                             
      ids(051)=8      ! specific humidity (kg/kg)                             
      ids(052)=1      ! relative humidity (percent)                           
!      ids(053)=6      ! humidity mixing ratio (kg/kg)                         
      ids(053)=9      ! humidity mixing ratio (kg/kg)                         
      ids(054)=2      ! precipitable water (kg/m2)                            
      ids(055)=0      ! vapor pressure (pa)                                   
      ids(056)=0      ! saturation deficit (pa)                               
      ids(057)=2      ! evaporation (kg/m2)                                   
      ids(058)=2      ! cloud ice (kg/m2)                                     
      ids(059)=7      ! precipitation rate (kg/m2/s)                          
      ids(060)=0      ! thunderstorm probability (percent)                    
      ids(061)=2      ! total precipitation (kg/m2)                           
      ids(062)=2      ! large-scale precipitation (kg/m2)                     
      ids(063)=2      ! convective precipitation (kg/m2)                      
      ids(064)=7      ! water equivalent snowfall rate (kg/m2/s)              
      ids(065)=1      ! water equivalent of snow depth (kg/m2)                
      ids(066)=3      ! snow depth (m)                                        
      ids(067)=2      ! ice water (kg/m2)                                   
      ids(068)=2      ! snow water (kg/m2)                                   
      ids(069)=2      ! graupel water (kg/m2)                                   
      ids(070)=2      ! hail water (kg/m2)                                   
      ids(071)=1      ! total cloud cover (percent)                           
      ids(072)=1      ! convective cloud cover (percent)                      
      ids(073)=1      ! low cloud cover (percent)                             
      ids(074)=1      ! middle cloud cover (percent)                          
      ids(075)=1      ! high cloud cover (percent)                            
      ids(076)=2      ! cloud water (kg/m2)                                   
      ids(077)=2      ! rain water (kg/m2)                                   
      ids(078)=2      ! convective snow (kg/m2)                               
      ids(079)=2      ! large scale snow (kg/m2)                              
      ids(080)=2      ! water temperature (k)                                 
      ids(081)=0      ! sea-land mask ()                                      
                      ! deviation of sea level from mean (m)                  
      ids(083)=6      ! roughness (m)                                         
      ids(084)=2      ! albedo (percent)                                      
      ids(085)=2      ! soil temperature (k)                                  
      ids(086)=1      ! soil wetness (kg/m2)                                  
      ids(087)=1      ! vegetation (percent)                                  
                      ! salinity (kg/kg)                                      
      ids(089)=5      ! density (kg/m3)                                       
      ids(090)=5      ! runoff (kg/m2)                                        
      ids(091)=1      ! ice concentration ()                                  
                      ! ice thickness (m)                                     
      ids(093)=0      ! direction of ice drift (degrees)                      
                      ! speed of ice drift (m/s)                              
                      ! u of ice drift (m/s)                                  
                      ! v of ice drift (m/s)                                  
                      ! ice growth (m)                                        
                      ! ice divergence (1/s)                                  
      ids(094)=9      ! SO2 concentration (kg/dryair-kg)                      
      ids(095)=9      ! SO4 concentration (kg/dryair-kg)                      
      ids(096)=9      ! Hydrophobic OC concentration (kg/dryair-kg)           
      ids(097)=9      ! Hydrophilic OC concentration (kg/dryair-kg)           
      ids(098)=9      ! Seasalt concentration (kg/dryair-kg)                  
      ids(099)=2      ! snow melt (kg/m2)                                     
                      ! sig height of waves and swell (m)                     
      ids(101)=0      ! direction of wind waves (degrees)                     
                      ! sig height of wind waves (m)                          
                      ! mean period of wind waves (s)                         
      ids(104)=0      ! direction of swell waves (degrees)                    
                      ! sig height of swell waves (m)                         
                      ! mean period of swell waves (s)                        
      ids(107)=0      ! primary wave direction (degrees)                      
                      ! primary wave mean period (s)                          
      ids(109)=0      ! secondary wave direction (degrees)                    
                      ! secondary wave mean period (s)                        
      ids(111)=1      ! net solar radiative flux at surface (w/m2)            
      ids(112)=1      ! net longwave radiative flux at surface (w/m2)         
      ids(113)=1      ! net solar radiative flux at top (w/m2)                
      ids(114)=1      ! net longwave radiative flux at top (w/m2)             
      ids(115)=1      ! net longwave radiative flux (w/m2)                    
      ids(116)=1      ! net solar radiative flux (w/m2)                       
      ids(117)=1      ! total radiative flux (w/m2)                           
      ids(118)=6      ! thermal roughness (m)
      ids(119)=6      ! perturbation of temperature (k)
      ids(120)=2      ! hydrostatic temperature (k)
                      !                                                       
      ids(121)=1      ! latent heat flux (w/m2)                               
      ids(122)=1      ! sensible heat flux (w/m2)                             
      ids(123)=1      ! boundary layer dissipation (w/m2)                     
      ids(124)=4      ! u wind stress (n/m2)                                  
      ids(125)=4      ! v wind stress (n/m2)                                  
                      ! wind mixing energy (j)                                
                      ! image data ()                                         
      ids(128)=0      ! mean sea-level pressure (stdatm) (pa)                 
      ids(129)=0      ! mean sea-level pressure (maps) (pa)                   
      ids(130)=0      ! mean sea-level pressure (eta) (pa)                    
      ids(131)=2      ! surface lifted index (k)                              
      ids(132)=2      ! best lifted index (k)                                 
      ids(133)=2      ! k index (k)                                           
      ids(134)=2      ! sweat index (k)                                       
      ids(135)=11     ! horizontal moisture divergence (kg/kg/s)              
      ids(136)=5      ! speed shear (1/s)                                     
      ids(137)=6      ! 3-hr pressure tendency (pa/s)                         
      ids(138)=7      ! brunt-vaisala frequency squared (1/s2)                
      ids(139)=12     ! potential vorticity (mass-weighted) (1/s/m)           
      ids(140)=0      ! rain mask ()                                          
      ids(141)=0      ! freezing rain mask ()                                 
      ids(142)=0      ! ice pellets mask ()                                   
      ids(143)=0      ! snow mask ()                                          
      ids(144)=4      ! volumetric soil moisture content (fraction)           
      ids(145)=6      ! potential evaporation rate (kg/m2/s)
      ids(146)=1      ! cloud workfunction (j/kg)                             
      ids(147)=4      ! u orography gravity wave stress (n/m2)                          
      ids(148)=4      ! v orography gravity wave stress (n/m2)                          
      ids(149)=11     ! potential vorticity (m2/s/kg)                         
      ids(150)=9      ! snow water (kg/kg)
      ids(151)=9      ! ice water (kg/kg)
      ids(152)=9      ! rain water (kg/kg)
      ids(153)=9      ! cloud water (kg/kg)
      ids(154)=9      ! ozone mixing ratio (kg/kg)
      ids(155)=1      ! ground heat flux (w/m2)                               
      ids(156)=1      ! convective inhibition (w/m2)                          
      ids(157)=1      ! convective ape (j/kg)                                 
      ids(158)=3      ! turbulent ke (j/kg)                                   
      ids(159)=2      ! progostic cloudiness 
      ids(160)=1      ! clear sky upward solar flux (w/m2)                    
      ids(161)=1      ! clear sky downward solar flux (w/m2)                  
      ids(162)=1      ! clear sky upward longwave flux (w/m2)                 
      ids(163)=1      ! clear sky downward longwave flux (w/m2)               
      ids(164)=1      ! cloud forcing net solar flux (w/m2)                   
      ids(165)=1      ! cloud forcing net longwave flux (w/m2)                
      ids(166)=1      ! visible beam downward solar flux (w/m2)               
      ids(167)=1      ! visible diffuse downward solar flux (w/m2)            
      ids(168)=1      ! near ir beam downward solar flux (w/m2)               
      ids(169)=1      ! near ir diffuse downward solar flux (w/m2)            
      ids(170)=4      ! u convection induced gravity wave stress (n/m2)
      ids(171)=4      ! v convection induced gravity wave stress (n/m2)
      ids(172)=4      ! momentum flux (n/m2)                                  
      ids(173)=0      ! mass point model surface ()                           
      ids(174)=0      ! velocity point model surface ()                       
      ids(175)=0      ! sigma layer number ()                                 
      ids(176)=2      ! latitude (degrees)                                    
      ids(177)=2      ! east longitude (degrees)                              
                      !                                                       
                      !                                                       
      ids(180)=6      ! actual evaporation rate (kg/m2/s)
      ids(181)=-3     ! number concentration of ccn (1/m3)
      ids(182)=-3     ! number concentration of qc (1/m3)
      ids(183)=-2     ! number concentration of qr (1/m3)
      ids(184)=6      ! y-gradient height (m/m)                               
                      !                                                       
                      !                                                       
                      !                                                       
      ids(188)=1      ! ground heat storage (W/m2)                            
      ids(190)=1      ! ocean mixed layer depth (m)                            
      ids(191)=1      ! aerosol distribution 
      ids(192)=1      ! aerosol profile type index
      ids(193)=1      ! First 2-layer aerosol number density
      ids(194)=1      ! aerosol components type indices
      ids(195)=6      ! aerosol components mixing ratio
                      !                                                       
                      !                                                       
                      !                                                       
                      !                                                       
                      !                                                       
      ids(201)=0      ! ice-free water surcace (percent)                      
      ids(202)=0      !                                                       
      ids(203)=0      !                                                       
      ids(204)=1      ! downward solar radiative flux (w/m2)                  
      ids(205)=1      ! downward longwave radiative flux (w/m2)               
                      !                                                       
      ids(207)=0      ! moisture availability (percent)                       
                      ! exchange coefficient (kg/m2/s)                        
      ids(209)=0      ! number of mixed layer next to sfc ()                  
                      !                                                       
      ids(211)=1      ! upward solar radiative flux (w/m2)                    
      ids(212)=1      ! upward longwave radiative flux (w/m2)                 
      ids(213)=0      ! non-convective cloud cover (percent)                  
      ids(214)=7      ! convective precipitation rate (kg/m2/s)               
      ids(215)=8      ! total diabatic heating rate (k/s)                     
      ids(216)=8      ! total radiative heating rate (k/s)                    
      ids(217)=8      ! total diabatic nonradiative heating rate (k/s)        
      ids(218)=2      ! precipitation index (fraction)                        
      ids(219)=2      ! std dev of ir t over 1x1 deg area (k)                 
      ids(220)=5      ! natural log of surface pressure over 1 kpa ()         
      ids(221)=1      ! planetary boundary layer height (m)                   
      ids(222)=1      ! 5-wave geopotential height (m)                        
      ids(223)=2      ! plant canopy surface water (kg/m2)                    
                      !                                                       
                      !                                                       
                      ! blackadars mixing length (m)                          
                      ! asymptotic mixing length (m)                          
      ids(228)=2      ! potential evaporation (kg/m2)                         
      ids(229)=1      ! snow phase-change heat flux (w/m2)                    
      ids(230)=1      ! snow evaporation (w/m2)                               
      ids(231)=4      ! convective cloud mass flux (pa/s)                     
      ids(232)=1      ! downward total radiation flux (w/m2)                  
      ids(233)=1      ! upward total radiation flux (w/m2)                    
      ids(224)=5      ! baseflow-groundwater runoff (kg/m2)                   
      ids(225)=0      ! vegetation type                          
      ids(226)=0      ! soil type                          
                      !                                                       
      ids(229)=1      ! snow phase change heat flux (w/m2)                    
      ids(230)=1      ! snow sublimation flux (w/m2)                          
      ids(236)=1      ! alternative latent heat flux (w/m2)                          
                                                                              
      ids(238)=1      ! snow cover (percent)                                  
      ids(239)=2      ! snow temperature (k)                                  
                      !                                                       
      ids(241)=8      ! large scale condensation heating rate (k/s)           
      ids(242)=8      ! deep convective heating rate (k/s)                    
      ids(243)=11     ! deep convective moistening rate (kg/kg/s)             
      ids(244)=8      ! shallow convective heating rate (k/s)                 
      ids(245)=11     ! shallow convective moistening rate (kg/kg/s)          
      ids(246)=8      ! vertical diffusion heating rate (kg/kg/s)             
      ids(247)=8      ! vertical diffusion zonal acceleration (m/s/s)         
      ids(248)=8      ! vertical diffusion merid acceleration (m/s/s)         
      ids(249)=11     ! vertical diffusion moistening rate (kg/kg/s)          
      ids(250)=8      ! solar radiative heating rate (k/s)                    
      ids(251)=8      ! longwave radiative heating rate (k/s)                 
                      ! drag coefficient ()                                   
                      ! friction velocity (m/s)                               
                      ! richardson number ()                                  
      ids(255)=6      ! graupel water (kg/kg)
                      !                                                       
   endif                                                                     
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -         
   return                                                                    
   end                                                                       
