   SUBROUTINE RDGB(LUGB,LGRIB,LSKIP,KPDS,KGDS,NDATA,LBMS,DATA,LUPTR)
!
!  READ GRIB FILE
!  INPUT
!    LUGB - LOGICAL UNIT TO READ
!    LGRIB - LENGTH OF GRIB RECORD
!    LSKIP - BYTES TO SKIP FOR GRIB RECORD
!  OUTPUT
!    KPDS(25) - UNPACKED PRODUCT DEFINITION SECTION
!    KGDS(22) - UNPACKED GRID DEFINITION SECTION
!    NDATA    - NUMBER OF DATA POINTS
!    LBMS(NDATA) - LOGICAL BIT MAP
!    DATA(NDATA) - DATA UNPACKED
!
   INTEGER, PARAMETER  ::  LLGRIB=2500*1250*4
 ! CHARACTER GRIB(LGRIB)*1
   CHARACTER           ::  GRIB(LLGRIB)*1
   INTEGER             ::  KPDS(25),KGDS(22),KPTR(16)
   LOGICAL*1           ::  LBMS(*)
   REAL                ::  DATA(*)
   NDATA=0
   CALL BAREAD(LUGB,LSKIP,LGRIB,LREAD,GRIB)
   IF(LREAD.LT.LGRIB) THEN
      WRITE(LUPTR,*) ' ERROR IN RDGB.  LREAD.LT.LGRIB'
      CALL ABORT
   ENDIF
   CALL W3FI63(GRIB,KPDS,KGDS,LBMS,DATA,KPTR,IRET)
   IF(IRET.NE.0) THEN
      WRITE(LUPTR,*) ' ERROR IN RDGB.  IRET.NE.0 from W3FI63'
      WRITE(LUPTR,*) ' IRET=',IRET
      CALL ABORT
   ENDIF
   NDATA=KPTR(10)
   RETURN
   END
