!-----------------------------------------------------------------------
   SUBROUTINE SKGB(LUGB,ISEEK,MSEEK,LSKIP,LGRIB)
!$$$  SUBPROGRAM DOCUMENTATION BLOCK
!
! SUBPROGRAM: SKGB           SEARCH FOR NEXT GRIB MESSAGE
!   PRGMMR: IREDELL          ORG: W/NMC23     DATE: 93-11-22
!
! ABSTRACT: THIS SUBPROGRAM SEARCHES A FILE FOR THE NEXT GRIB 1 MESSAGE.
!   A GRIB 1 MESSAGE IS IDENTIFIED BY ITS INDICATOR SECTION, I.E.
!   AN 8-BYTE SEQUENCE WITH 'GRIB' IN BYTES 1-4 AND 1 IN BYTE 8.
!   IF FOUND, THE LENGTH OF THE MESSAGE IS DECODED FROM BYTES 5-7.
!   THE SEARCH IS DONE OVER A GIVEN SECTION OF THE FILE.
!   THE SEARCH IS TERMINATED IF AN EOF OR I/O ERROR IS ENCOUNTERED.
!
! PROGRAM HISTORY LOG:
!   93-11-22  IREDELL
!   95-10-31  IREDELL   ADD CALL TO BAREAD 
!
! USAGE:    CALL SKGB(LUGB,ISEEK,MSEEK,LSKIP,LGRIB)
!   INPUT ARGUMENTS:
!     LUGB         INTEGER LOGICAL UNIT OF INPUT GRIB FILE
!     ISEEK        INTEGER NUMBER OF BYTES TO SKIP BEFORE SEARCH
!     MSEEK        INTEGER MAXIMUM NUMBER OF BYTES TO SEARCH
!   OUTPUT ARGUMENTS:
!     LSKIP        INTEGER NUMBER OF BYTES TO SKIP BEFORE MESSAGE
!     LGRIB        INTEGER NUMBER OF BYTES IN MESSAGE (0 IF NOT FOUND)
!
! SUBPROGRAMS CALLED:
!   BAREAD       BYTE-ADDRESSABLE READ
!   GBYTE        GET INTEGER DATA FROM BYTES
!
! ATTRIBUTES:
!   LANGUAGE: FORTRAN
!
!$$$
   INTEGER, PARAMETER  ::  LSEEK=128
   CHARACTER           ::  Z(LSEEK)
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   LGRIB=0
   KS=ISEEK
   KN=MIN(LSEEK,MSEEK)
   KZ=LSEEK
   DO WHILE(LGRIB.EQ.0.AND.KN.GE.8.AND.KZ.EQ.LSEEK)
      CALL BAREAD(LUGB,KS,KN,KZ,Z)
!     print *,'After BAREAD'
!     print *,(Z(I),I=1,20)
      KM=KZ-8+1
      K=0
      DO WHILE(LGRIB.EQ.0.AND.K.LT.KM)
         CALL GBYTE(Z,I4,(K+0)*8,4*8)
         CALL GBYTE(Z,I1,(K+7)*8,1*8)
!        IF(K.EQ.1) THEN
!            print *,'I4=',I4,' I1=',I1
!            print *,(Z(I),I=1,20)
!        ENDIF
         IF(I4.EQ.1196575042.AND.I1.EQ.1) THEN
            LSKIP=KS+K
            CALL GBYTE(Z,LGRIB,(K+4)*8,3*8)
          ! print *,'word "GRIB" found'
         ENDIF
         K=K+1
      ENDDO
      KS=KS+KM
      KN=MIN(LSEEK,ISEEK+MSEEK-KS)
   ENDDO
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   RETURN
   END
